
apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
  namespace: activity2
spec:
  selector:
    app: step2
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 31769
  type: NodePort